name: BACNet/SC tests

on: [push, pull_request]

jobs:
  job_bsc_tests_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Build Environment
      run: |
        vcpkg install libwebsockets --triplet x64-windows
    - name: Setup MSBuild 
      uses: microsoft/setup-msbuild@v1.1
      with:
        msbuild-architecture: x64
    - name: Build and run bvlc-sc test
      run: |
        cd ./test/bacnet/datalink/bvlc-sc
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake
        msbuild build/test_bvlc-sc.sln /Property:Configuration=Release
        ./build/Release/test_bvlc-sc.exe
    - name: Build and run websockets test
      run: |
        cd ./test/bacnet/datalink/websockets
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake
        msbuild build/test_websockets.sln /Property:Configuration=Release
        ./build/Release/test_websockets.exe
    - name: Build and run bsc-socket test
      run: |
        cd ./test/bacnet/datalink/bsc-socket
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake
        msbuild build/test_bsc-socket.sln /Property:Configuration=Release
        ./build/Release/test_bsc-socket.exe
    - name: Build and run hub-sc test
      run: |
        cd ./test/bacnet/datalink/hub-sc
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake
        msbuild build/test_hub-sc.sln /Property:Configuration=Release
        ./build/Release/test_hub-sc.exe
    - name: Build and run bsc-node test
      run: |
        cd ./test/bacnet/datalink/bsc-node
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake
        msbuild build/test_bsc-node.sln /Property:Configuration=Release
        ./build/Release/test_bsc-node.exe
    - name: Build and run bsc-datalink test
      run: |
        cd ./test/bacnet/datalink/bsc-datalink
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=c:\vcpkg\scripts\buildsystems\vcpkg.cmake
        msbuild build/test_bsc-datalink.sln /Property:Configuration=Release
        ./build/Release/test_bsc-datalink.exe
  job_bsc_tests_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Build Environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq libconfig-dev
        sudo apt-get install -qq libcap-dev
        sudo apt-get install -qq libssl-dev
        git clone https://libwebsockets.org/repo/libwebsockets
        bash -c 'cd libwebsockets;mkdir build;cd build;cmake ..;make'
        sudo bash -c 'cd libwebsockets;cd build;make install'
    - name: Build and run bvlc-sc test
      run: |
        cd ./test/bacnet/datalink/bvlc-sc
        mkdir build
        cd build
        cmake ..
        make
        ./test_bvlc-sc
    - name: Build and run websockets test
      run: |
        cd ./test/bacnet/datalink/websockets
        mkdir build
        cd build
        cmake ..
        make
        ./test_websockets
    - name: Build and run bsc-socket test
      run: |
        cd ./test/bacnet/datalink/bsc-socket
        mkdir build
        cd build
        cmake ..
        make
        ./test_bsc-socket
    - name: Build and run hub-sc test
      run: |
        cd ./test/bacnet/datalink/hub-sc
        mkdir build
        cd build
        cmake ..
        make
        ./test_hub-sc
    - name: Build and run bsc-node test
      run: |
        cd ./test/bacnet/datalink/bsc-node
        mkdir build
        cd build
        cmake ..
        make
        ./test_bsc-node
    - name: Build and run bsc-datalink test
      run: |
        cd ./test/bacnet/datalink/bsc-datalink
        mkdir build
        cd build
        cmake ..
        make
        ./test_bsc-datalink
  job_bsc_tests_macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Build Environment
      run: |
        brew install libwebsockets
    - name: Build and run bvlc-sc test
      run: |
        cd ./test/bacnet/datalink/bvlc-sc
        mkdir build
        cd build
        cmake ..
        make
        ./test_bvlc-sc
    - name: Build and run websockets test
      run: |
        cd ./test/bacnet/datalink/websockets
        mkdir build
        cd build
        cmake ..
        make
        ./test_websockets
    - name: Build and run bsc-socket test
      run: |
        cd ./test/bacnet/datalink/bsc-socket
        mkdir build
        cd build
        cmake ..
        make
        ./test_bsc-socket
    - name: Build and run hub-sc test
      run: |
        cd ./test/bacnet/datalink/hub-sc
        mkdir build
        cd build
        cmake ..
        make
        ./test_hub-sc
    - name: Build and run bsc-node test
      run: |
        cd ./test/bacnet/datalink/bsc-node
        mkdir build
        cd build
        cmake ..
        make
        ./test_bsc-node
    - name: Build and run bsc-datalink test
      run: |
        cd ./test/bacnet/datalink/bsc-datalink
        mkdir build
        cd build
        cmake ..
        make
        ./test_bsc-datalink
