name: BSC_Test

on: [push, pull_request]

jobs:
  job_bsc_linux_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create Build Environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install -qq libconfig-dev
        sudo apt-get install -qq libcap-dev
        sudo apt-get install -qq libssl-dev
        git clone https://libwebsockets.org/repo/libwebsockets
        bash -c 'cd libwebsockets;mkdir build;cd build;cmake ..;make'
        sudo bash -c 'cd libwebsockets;cd build;make install'
    - name: bvlc-sc
      run: |
        cd ./test/bacnet/datalink/bvlc-sc
        mkdir build
        cd build
        cmake ..
        make
        ./test_bvlc-sc
    - name: websockets
      run: |
        cd ./test/bacnet/datalink/websockets
        mkdir build
        cd build
        cmake ..
        make
        ./test_websockets
    - name: hub-sc
      run: |
        cd ./test/bacnet/datalink/hub-sc
        mkdir build
        cd build
        cmake ..
        make
        ./test_hub-sc
